project_id = "aoyqeieqqmpuhfvfzbrb"

[functions.tradingview-webhook]
verify_jwt = false

[functions.bitget-trader]
verify_jwt = true

[functions.bitget-api]
verify_jwt = true

[functions.position-monitor]
verify_jwt = true

[functions.close-position]
verify_jwt = true

[functions.import-history]
verify_jwt = true

[functions.recalculate-sltp]
verify_jwt = false

[functions.emergency-shutdown]
verify_jwt = true

[functions.sync-positions-history]
verify_jwt = false

[functions.repair-history-data]
verify_jwt = false

[functions.repair-positions-history]
verify_jwt = true

[functions.fix-positions-data]
verify_jwt = true

[functions.link-positions-alerts]
verify_jwt = true

[functions.repair-mm-data]
verify_jwt = true
