project_id = "aoyqeieqqmpuhfvfzbrb"

[functions.tradingview-webhook]
verify_jwt = false

[functions.bitget-trader]
verify_jwt = true

[functions.bitget-api]
verify_jwt = true

[functions.position-monitor]
verify_jwt = true

[functions.close-position]
verify_jwt = true

[functions.import-history]
verify_jwt = true